server:
  port: 20240
  servlet:
    context-path: /emp-jsp
    jsp:
      init-parameters:
        development: true
        
spring:
  datasource:
    type:  com.zaxxer.hikari.HikariDataSource #spring默认的连接池
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/empjsp?characterEncoding=UTF-8
    username: root
    password: 5312448th
  mvc:
    view:
      prefix:  /
      suffix:  .jsp

logging:
  level:
    root: info
    '[com.eden]': debug
    
mybatis:
  mapper-locations:  classpath:com/eden/mapper/*.xml
  type-aliases-package:  com.eden.entity